const:
  default-page-size: 20


file:
  directory: D:/download/greengram_ver3

jwt:
  issuer: green@green.kr
  secret-key: studydjgsfdsfdgisgi687dssfd8798y69998898says9798sday8asd7a0as98tsa8tda8ta8st8sadt8da98sa98dasspringbootjlsdjaspa

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer3

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502
  Jackson:
    default-property-inclusion: non_null # 응답 JSON 을 만들떄 NULL 인 속성은 제외


  servlet:
    multipart:
      max-file-size: 15MB
      maxRequestSize: 30MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true